gc_interval : 20  # Intervalo entre o final de uma operação de GC e o inicio de outra
usage_interval : 5 # Time in seconds to update the usage couters

cache_size : 1000  # Cache size in entries. Memory size is ~cache_size*allocation_unit
small_block_cache_size : 1000

allocation_unit : 1024

mean_blk_size : 128
#min_blk_size : 32 # Auto calculated by the system
#max_blk_size : 512 # Auto calculated by the system
small_block_limit : 32 #4096  # Blocos com tamanho igual ou menor que este não serão compactados e serão armazenados em um local diferente especificado em small_block_path

partition_size : 5  # Partion size in GB
chunk_size_per_GB : 1 # Tamanho de cada um dos chunks TODO: How does this handles fractions?

# Location where the data will be stored
# fs_meta_path, hash_table_path, free_blocks_path en gc_path are all metadata
# small_blocks_db_path and datastore_base_path are block store locations
# MMAP backend use all the stores
# RocksDB backend, use only fs_meta_path, hash_table_path and datastore_base_path

# datastore_base_path and small_block_db_path can be a list with multiply locations
# the system will spreads the reads and writes between this locations to improve
# safety and performance
# In cases of a non-even distribution, the system will give preference to store the last chunks in
# the order that the datastores are entered in the list
# Datastore sizes are symmetrical and and defined at *chunk_size_per_gb*

fs_meta_path : '/home/jmarceno/metadata/filesystem'
hash_table_path : '/home/jmarceno/metadata/hashtable'
free_blocks_path : '/home/jmarceno/metadata/freeblocks'
gc_path : '/home/jmarceno/metadata/gc'
small_block_db_path : ['/home/jmarceno/metadata/smbs']
datastore_base_path : ['/home/jmarceno/metadata/meta01',/run/media/jmarceno/Vault/linux_back/metadata/meta02]

# Indicates if the system will keep an additional copy of the metadata
# Writes will be done in sync. Reads will only be performed at the original
# Notes:
# 1. This almost double the amount of data taken by the metadata
# 2. Causes a slight increased in persistence latency, wich can reduce write speeds, but impact here is minimal
replicate_metadata: True
fsmeta_replication_path: '/run/media/jmarceno/Vault/linux_back/metadata/mirror/fsmeta'
hashtable_replication_path: '/run/media/jmarceno/Vault/linux_back/metadata/mirror/hashtable'

#TODO: Implement data replication
#TODO: Implement the option to use the replicated copy to speed up reads (aka Read Spread)
# Indicates if the system will keep an additional copy of the data
# Writes will be done in sync. Reads will only be performed at the original
# Ideally the same number of paths given at *datastore_base_path* should be given here,
# but the system will work with any number of paths.
# Note that *write spread* is applied here too
replicate_data: False
data_replication_path: ['/run/media/jmarceno/Vault/linux_back/metadata']

#TODO: Implement path aware datastore distribuition
# If *False*, the system will write to a datastore until it is full
# only then, moving to the next one
# If *True*, the system will try to spread all the writes evenly through all the datastores.
# For better performance, *Enable* if datastores are on different disks/machines, disable otherwise
write_spread: True

# Used on the datastore to ini
identity_string : 'VeratyFS@v0.0.1@InLineDedup,FixedStoreSize,GC,Compression,FixedBlockSize\n'

q_random : 2 # Maximum number of the random range to the tested against to decided if one of the spammy messages will make to the queue

web_interface : 'localhost:5555'
log_file : /home/jmarceno/metadata/logs.txt

# Storage Backend for data persistance
# Options:
# 'mmap': Data will be stored into chunks and persisted through a mmap interface -> Fast, fragmentation prone
# 'rocksdb': (*RECOMMENDED*) Data will be stored into various rocksdb databases -> Not as fast as mmap but *safer* and does not suffer from fragmention
backend: 'rocksdb'

# Maximum number of write worker threads, responsible to flush data to disk
# Increase this number in line with the number of cores and disks that the system has access to
# More disks == More write workers (1-5 per disk is recommended)
max_write_workers: 11