gc_interval : 20  # Intervalo entre o final de uma operação de GC e o inicio de outra
usage_interval : 5 # Time in seconds to update the usage couters

cache_size : 10000  # Cache size in entries. Memory size is ~cache_size*allocation_unit
small_block_cache_size : 10000

allocation_unit : 1024

mean_blk_size : 64
min_blk_size : 16
max_blk_size : 512
small_block_limit : 8192 #4096  # Blocos com tamanho igual ou menor que este não serão compactados e serão armazenados em um local diferente especificado em small_block_path

partition_size : 6  # Partion size in GB
chunk_size_per_GB : 2 # Tamanho de cada um dos chunks TODO: How does this handles fractions?

fs_meta_path : '/home/jmarceno/metadata/filesystem'
hash_table_path : '/home/jmarceno/metadata/hashtable'
free_blocks_path : '/home/jmarceno/metadata/freeblocks'
gc_path : '/home/jmarceno/metadata/gc'
small_block_db_path : '/home/jmarceno/metadata/smbs'
datastore_base_path : '/home/jmarceno/metadata/'

identity_string : 'VeratyFS@v0.0.1@InLineDedup,FixedStoreSize,GC,Compression,FixedBlockSize\n'

q_random : 2 # Maximum number of the random range to the tested against to decided if one of the spammy messages will make to the queue

web_interface : 'localhost:5555'

log_file : /home/jmarceno/metadata/logs.txt